sudo: false
addons:
  apt:
    packages:
    - lmodern
    - texlive-latex-recommended
    - texlive-latex-extra
    - texlive-fonts-extra
    - texlive-fonts-recommended
    - texlive-xetex
    - texlive-science
script:
  - cd src
  - make test
